# Generated by Django 4.1.1 on 2022-10-03 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacienteApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oximetria', models.FloatField(default=0, null=True, verbose_name='Oximetria')),
                ('temperatura', models.FloatField(default=0, null=True, verbose_name='Temperatura')),
                ('frecuencia_respiratoria', models.FloatField(default=0, null=True, verbose_name='FrecuenciaRespiratoria')),
                ('glicemia', models.FloatField(default=0, null=True, verbose_name='Glicemia')),
                ('comentario_medico', models.CharField(default='Sin comentario medico', max_length=2000, null=True, verbose_name='ComentarioMedico')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacienteApp.paciente')),
            ],
        ),
    ]
