# Generated by Django 4.1.1 on 2022-10-03 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profesionalApp', '0003_alter_profesionalmedico_id_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pacienteApp', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='id_profesional_medico',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='profesionalApp.profesionalmedico'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
