from .actualizarProfesionalView import ActualizarProfesionalView
from .consultarProfesionalView import ConsultarProfesionalView
from .consultarProfesionalesView import ConsultarProfesionalesView
from .crearProfesionalView import CrearProfesionalView
from .eliminarProfesionalView import EliminarProfesionalView
from .obtenerProfesionalView import ObtenerProfesionalView