# Generated by Django 4.1.1 on 2022-10-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auxiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sin nombre', max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(default='Sin apellido', max_length=50, verbose_name='Apellido')),
            ],
        ),
    ]
