from .actualizarFamiliarAsignadoView import ActualizarFamiliarAsignadoView
from .consultarFamiliarAsignadoView import ConsultarFamiliarAsignadoView
from .crearFamiliarAsignadoView import CrearFamiliarAsignadoView
from .eliminarFamiliarAsignadoView import EliminarFamiliarAsignadoView
from .obtenerFamiliarAsignadoView import ObtenerFamiliarAsignadoView