from .actualizarPacienteView import ActualizarPacienteView
from .consultarPacienteView import  ConsultarPacienteView
from .consultarPacientesView import ConsultarPacientesView
from .consultarPacientesPorProfesionalMedicoView import ConsultarPacientesPorProfesionalMedicoView
from .consultarPacientesPorFamiliar import ConsultarPacientesPorFamiliar
from .crearPacienteView import CrearPacienteView
from .eliminarPacienteView import EliminarPacienteView
from .obtenerPacienteView import ObtenerPacienteView